### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by ThKaspar** [ThKaspar/BilleCAR#22]
Po zalogowaniu użytkownika bez przeładowania strony zapytania do API zwracają kod 401 (Unauthorized).

Nagłówki: {"Authorization":"undefined undefined","Accept":"application/json, text/plain, */*"}.

**Comment by ThKaspar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [401 Unauthorized](https://trello.com/c/DjkFIYaF/62-401-unauthorized)

**Comment by zioomek993** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Poprawki web](https://trello.com/c/8OCSmjKC/73-poprawki-web)

**Comment by zioomek993** [comment]
Naprawione
