### ISSUE TITLE
Brak akcji

### ISSUE THREAD

**Issue by NiNe94** [ThKaspar/BilleCAR#25]
Po zalogowaniu sie do systemu, i wybraniu opcji "MOje ogloszenia" nie jestesmy w stanie potem przejsc na inne podstrony przy uzyciu przycisków trzeba odswiezac strone by moc kontynuowac.

**Comment by ThKaspar** [comment]
Działa jeśli przejdziesz Moje Ogłoszenia > Strona Główna > Ogłoszenia. Tylko bezpośrednio z Moich Ogłoszeń nie możesz.

**Comment by zioomek993** [comment]
done
