### ISSUE TITLE
Problem z wyszukiwaniem po miejscowościach 

### ISSUE THREAD

**Issue by zioomek993** [ThKaspar/BilleCAR#28]
Problem z wyszukiwaniem w przypadku podania nazwy w innym formacie niż pierwsza duża litera reszta małe.

**Comment by zioomek993** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Naprawić wyszukiwanie](https://trello.com/c/OflYdz81/69-naprawic-wyszukiwanie)

**Comment by ThKaspar** [comment]
Poprawione - wyszukiwanie ignoruje rozmiar liter.
