### ISSUE TITLE
Wyszukiwanie i filtrowanie

### ISSUE THREAD

**Issue by NiNe94** [ThKaspar/BilleCAR#32]
Gdy wybieram jako miejsce poczatkowe jakies Miasto , nastepnie chce wyfiltrowac je po jakims filtrze, opcja z szukaj zostaje anulowana i zostaja zwrocone przejazdy wyfiltrowane po jakis filtrach

**Comment by ThKaspar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Filtrowanie po samych godzinach](https://trello.com/c/aTIPQQRg/70-filtrowanie-po-samych-godzinach)

**Comment by ThKaspar** [comment]
Poprawione - wyszukiwanie po dacie i godzinie zostało rozdzielne
