### ISSUE TITLE
Zmiany w layoucie / bledy

### ISSUE THREAD

**Issue by NiNe94** [ThKaspar/BilleCAR#33]
- przy ogloszeniach <Strzalki do zamiany> po najechaniu kursor powinien zmieniac swoja postac na tzw "lapke" niestety jest w postaci jakby dawal do zrozumienia ze te pole jest tekstowe i mozna w nim pisac 
(nie wiem jak to lepiej okreslic :P)

- zmienic modal przy dodawaniu ogloszenia ( zwiekszyc rozmiar by nie przesuwac tego ekranu) przy responsywnym ukladzie Etykieta pola pokrywa sie z dolnym borderem 

- przy Wiecej szczegolow przy ogloszeniu rowniez zmienic modal na wiekszy by nie trzeba bylo scrollowac , oraz Imie i Nazwisko pojawia sie dwukrotnie.

- pozamieniac LABELe na PLACEHOLDERy

**Comment by zioomek993** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Poprawki widoków](https://trello.com/c/rjV9Xvev/72-poprawki-widokow)

**Comment by loocasch** [comment]
zrobione
